name: Deploy Flask App

on:
  push:
    branches:
      - main  # or the branch you want to deploy from
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Flask app (for testing purposes)
      - name: Run Flask app
        run: |
          export FLASK_APP=app.py
          export FLASK_ENV=development
          flask run --host=0.0.0.0 --port=5000
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
          
      # Optional: Step to run tests
      # - name: Run tests
      #   run: |
      #     pytest  # If you have tests set up
